sudo: false

language: python

python:
  - "3.5"
  - "3.6"
  
before_install:
  - pip install pytest-cov
  
env:
  - PYTHONPATH="."
  
script: 
  - pytest
  - pytest --cov=./

after_success:
  - codecov
